package routes

import (
	"github.com/gin-gonic/gin"
	"github.com/phone_management/internal/auth"
	"github.com/phone_management/internal/handlers"
	"github.com/phone_management/internal/repositories"
	"github.com/phone_management/internal/services"
	"gorm.io/gorm"

	_ "github.com/phone_management/docs" // docs is generated by Swag CLI, you have to import it.
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Phone Management API
// @version 1.0
// @description This is a sample server for a phone management system.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

// SetupRouter 配置所有应用路由
func SetupRouter(db *gorm.DB) *gin.Engine {
	r := gin.Default()

	// CORS 中间件 (如果需要)
	// r.Use(cors.Default())

	// JWT 中间件实例化
	jwtAuthMiddleware := auth.JWTMiddleware()

	// 创建 /api/v1 路由组
	apiV1 := r.Group("/api/v1")
	{
		// --- 认证路由 ---
		authGroup := apiV1.Group("/auth")
		{
			// POST /api/v1/auth/login - 公开路由，不需要JWT
			authGroup.POST("/login", handlers.Login)

			// POST /api/v1/auth/logout - 受保护路由，需要JWT
			// LogoutHandler 内部会处理JTI，所以应用JWT中间件
			authGroup.POST("/logout", jwtAuthMiddleware, handlers.LogoutHandler)
		}

		// --- 员工路由 (先初始化，因为 MobileNumberService 依赖它) ---
		employeeRepo := repositories.NewGormEmployeeRepository(db)
		employeeService := services.NewEmployeeService(employeeRepo)
		employeeHandler := handlers.NewEmployeeHandler(employeeService)

		// --- 手机号码路由 ---
		// 初始化手机号码相关的 repository, service, handler
		mobileNumberRepo := repositories.NewGormMobileNumberRepository(db)
		// 将 employeeService 注入到 MobileNumberService
		mobileNumberService := services.NewMobileNumberService(mobileNumberRepo, employeeService)
		mobileNumberHandler := handlers.NewMobileNumberHandler(mobileNumberService)

		mobileNumbersGroup := apiV1.Group("/mobilenumbers")
		mobileNumbersGroup.Use(jwtAuthMiddleware) // 对整个 /mobilenumbers 路由组应用 JWT 中间件
		{
			// POST /api/v1/mobilenumbers/
			mobileNumbersGroup.POST("/", mobileNumberHandler.CreateMobileNumber)
			// GET /api/v1/mobilenumbers/
			mobileNumbersGroup.GET("/", mobileNumberHandler.GetMobileNumbers)
			// GET /api/v1/mobilenumbers/:phoneNumber
			mobileNumbersGroup.GET("/:phoneNumber", mobileNumberHandler.GetMobileNumberByID)
			mobileNumbersGroup.POST("/:phoneNumber/update", mobileNumberHandler.UpdateMobileNumber)
			mobileNumbersGroup.POST("/:phoneNumber/assign", mobileNumberHandler.AssignMobileNumber)
			mobileNumbersGroup.POST("/:phoneNumber/unassign", mobileNumberHandler.UnassignMobileNumber)
			// POST /api/v1/mobilenumbers/import 批量导入手机号码
			mobileNumbersGroup.POST("/import", mobileNumberHandler.BatchImportMobileNumbers)
		}

		// --- 员工路由组定义放在后面，但初始化已提前 ---
		employeeRoutes := apiV1.Group("/employees")
		employeeRoutes.Use(jwtAuthMiddleware)
		{
			employeeRoutes.POST("/", employeeHandler.CreateEmployee)
			employeeRoutes.GET("/", employeeHandler.GetEmployees)
			employeeRoutes.GET("/:employeeId", employeeHandler.GetEmployeeByID)
			// POST /api/v1/employees/:employeeId/update
			employeeRoutes.POST("/:employeeId/update", employeeHandler.UpdateEmployee)
			// POST /api/v1/employees/import 批量导入员工
			employeeRoutes.POST("/import", employeeHandler.BatchImportEmployees)
		}

	}

	// Swagger 文档路由 (如果使用 swaggo)
	// r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, ginSwagger.URL("/swagger/doc.json")))

	return r
}
